language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
script:
  - commitlint-travis
  - yarn lint
  - yarn test
  - yarn codecov
  - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn pages; fi
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GH_TOKEN
    local-dir: pages
    on:
      branch: master
