language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 10
  - 8
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: validate
      script: commitlint-travis
      script: yarn lint
      script:
        - yarn test
        - yarn codecov
      script: yarn build
    - stage: release
      node_js: lts/*
      script: npm run semantic-release
    - stage: ghpages
      script: then yarn pages; fi
      deploy:
        provider: pages
        skip-cleanup: true
        keep-history: true
        github-token: $GH_TOKEN
        local-dir: pages
stages:
  - validate
  - name: release
    if: branch = master
  - name: ghpages
    if: branch = master