language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: lint
      script:
        - commitlint-travis
        - yarn lint
        - yarn build
    - stage: test
      script: yarn test &&  yarn codecov
    - stage: release
      if: branch = master AND env(TRAVIS_PULL_REQUEST) = false
      node_js: lts/*
      script:  yarn semantic-release;
    - stage: ghpages
      if: branch = master AND env(TRAVIS_PULL_REQUEST) = false
      script: yarn pages;
      deploy:
        provider: pages
        skip-cleanup: true
        keep-history: true
        github-token: $GH_TOKEN
        local-dir: pages
        on:
          branch: master
stages:
  - lint
  - test
  - release
  - ghpages