sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - commitlint-travis
  - yarn lint
  - yarn test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then yarn docs; fi
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    github-token: $GH_TOKEN
    local-dir: docs
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script:
      - lerna publish
    on:
      branch: master
