language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: lint
      script:
        - commitlint-travis
        - yarn lint
        - yarn build
    - stage: test
      script: yarn test &&  yarn codecov
    - stage: release
      node_js: lts/*
      script: npm run semantic-release
    - stage: ghpages
      script: yarn pages;
      deploy:
        provider: pages
        skip-cleanup: true
        keep-history: true
        github-token: $GH_TOKEN
        local-dir: pages
stages:
  - lint
  - test
  - name: release
    if: branch = master AND env(TRAVIS_PULL_REQUEST) = "false"
  - name: ghpages
    if: branch = master AND env(TRAVIS_PULL_REQUEST) = "false"